#!/bin/bash

usage () {
    echo "$0 -s [--sport] < serial_port >"
    exit 1
}

if [ $# != 2 ]; then
    echo "Not enough arguments supplied!"
    usage
fi

case "$1" in
        -s)
            cd python
            python emg_main.py $1 $2
            ;;
        *)
            usage
esac
